### PR TITLE
(major) Restrict number of newlines

### PR DESCRIPTION
**Pull request by MitMaro**
- zero padding newlines at top of file
- zero padding newlines at bottom of file
- disallow multiple consecutive newlines in file

This will require a major version bump.

### CODE REVIEW

**Comment by dvalentiate** [comment]
approved assuming this doesn't impede the requirement to have a newline at the end of a file

**Comment by MitMaro** [comment]
In my tests it did not. I think it's zero empty lines at the end of the file, where a newline character is attached to the line previous.

**Comment by erinwu** [comment]
approved

**Comment by dvalentiate** [comment]
approved

**Pull request merged**
