### PR TITLE
Release version 6.0.0

### PR DESCRIPTION
**Pull request by jackharrhy**
- Update date in LICENCE

### CODE REVIEW

**Comment by jackharrhy** [comment]
> packge-lock.json needs update with the new version number

c935f067a15d90c5f679f38c007b1d1760602891

**Comment by jackharrhy** [comment]
> packge-lock.json needs update with the new version number

c935f067a15d90c5f679f38c007b1d1760602891

**Comment by MitMaro** [comment]
Let me know when this is merged and I will publish the release.

**Comment by MitMaro** [comment]
Oh! Past me was a pretty decent guy and setup deployment based on tags. You should be able to create a release and it should auto-deploy.

**Pull request merged**
