### PR TITLE
Eslint updates 3

### PR DESCRIPTION
**Pull request by MitMaro**

### CODE REVIEW

**Comment by dvalentiate** [comment]
did the single quote become invalid as a string holder? Why all the conversion to backticks?

**Comment by MitMaro** [comment]
@dvalentiate There was a move towards using template strings only in one of our new purely ES6 projects. I have no opinion one way or the other, just following along some of the rules laid out there.

**Comment by dvalentiate** [comment]
I'm not asking if they are valid. Why switch a lot of single quotes to backtickets. They are annoying to type and have more complex behaviour for no gain when converting something like 'value' to `value`. Template strings definitely are useful at times but I don't understand why you switched things like 'off' to `off`.

**Comment by MitMaro** [comment]
@whymarrh made that decision. I will have to get him to defend it.

**Comment by dvalentiate** [comment]
`promise/no-native` should be `off`. Promises are part of the language.

**Comment by dvalentiate** [comment]
`no-process-env` set to `error` is annoying. On a big project is it very valid to limit the use of environment variables to something like a config file, however when writing scripts using `process.env` is normal and ok.

Just imagine trying to write a `.sh` script without using ENVIRONMENT variables because "those are supposed to be put in a config file".

I'm open to discussion on this.

**Comment by dvalentiate** [comment]
`no-console` is common and ok in scripts, not so much in product code. It is annoying to have it outlawed.

**Comment by dvalentiate** [comment]
`promise/always-return` should not be set to `error`. It is common for a promise to not return a value. Such as `.then((data) => {console.log(data);})`

**Comment by whymarrh** [comment]
> `promise/no-native` should be `off`. Promises are part of the language.

I agree that native `Promise` should be allowed. I *think* the reason behind this is that the team uses [bluebird](http://bluebirdjs.com/) in almost all cases, though I guess we might want `warn` here instead, to your point.

> `no-process-env` is set to `error` and that is annoying. On a big project is it very valid to limit the use of environment variables to something like a config file, however when writing scripts using `process.env` is normal and ok.
> 
> Just imagine trying to write a `.sh` script without using env vars because "those are supposed to be put in a config file".

I think the setting is supposed to annoying in a sense. I also don't follow how that relates to shell scripts... they're two very different languages used differently. Nonetheless, having `process.env` isolated to a particular config file *is* the goal and `error` helps us get there. We can [disable it per line or per file][1] as needed.

> `console.log`, and `console.error` are common and ok in scripts, not so much in product code. It is annoying to have it outlawed with `no-console` set to `error`.

I think this is fine and it's supposed to be annoying. If we need to have a log call in production code we can [allow it for a particular line or for a whole file][1] (in the case of a script).

> `promise/always-return` should not be set to `error`. It is common for a promise to not return a value. Such as `.then((data) => {console.log(data);})`

Well your example doesn't make much sense because `console.log` is set to `error` (just kidding). Joking aside, in cases where it makes sense to not return a value I think requiring the author to `return undefined;` (or `return null;`, `return true;`, or the like) to make the choice explicit is good. (As a side note going back to the first comment on native `Promise`: bluebird has [`.tap`][2] which is useful for cases where you want a side-effect and don't want to return a value.)

  [1]:http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments
  [2]:http://bluebirdjs.com/docs/api/tap.html

**Comment by dvalentiate** [comment]
I don't use `Bluebird` because it has been an easily dispensed with dependency in the projects I've worked on recently. Got nothing against it in bigger projects. But again in small things Bluebird is just bloat.

Let me state it again: Promises are part of the native language. Not an error and not a warning. They are valid and good practice. Bluebird's convention of declaring itself as a native keyword is sketchy (backwards compatibility aside). It is like declaring `var Number = {...};` and thinking that is a good idea.

**Comment by dvalentiate** [comment]
per line exceptions for `no-process-env`, and `no-cosole` is where I expect this to end up. It is reasonable. I'll just declare .eslintrc `off` rules for those settings in the small repos where doing the per line thing is more distracting than beneficial.

**Comment by dvalentiate** [comment]
`promise/always-return` should be set `off`.  Every chain of promises has a end `.then`. At this point there is nothing left to absorb a return. So it is very common to not have a return value. Like "every time a promise chain is used" common. Bluebird's `tap` is intended for different purposes.

**Comment by whymarrh** [comment]
> `promise/always-return` should be set `off`. Every chain of promises has a end `.then`. At this point there is nothing left to absorb a return. So it is very common to not have a return value. Like "every time a promise chain is used" common. Bluebird's `tap` is intended for different purposes.

If you're trying to log a value, bluebird's `tap` might be the best option. That said, yes, every promise chain does indeed end *somewhere* with a final call to `.then` but it's not always clear where that is unless the promise is created and used in a single place. For example:

```js
function foo(p) {
    return p.then(() => { doThing(); });
}
```

Is that *supposed* to return a promise? Is that the final `.then` in the chain? One *can* chain things off of the result of `foo()` and when they do they might be expecting an input value to their function.

Anyhow, a promise in isolation:

```js
function foo() {
    const a = 42;
    const p = Promise.resolve(someGlobal)
        .then(val => { tellSomethingAboutTheGlobal(val); });
    return {
        'foo': 'bar',
    };
}
```

While, yes, as shown above, the creation and use of a promise in a single place does make sense to not have a return statement, that isn't very common. It might be more common to see something like so (which brings us back to not knowing whether this chain is continued elsewhere):

```js
function foo() {
    const a = 42;
    return Promise.resolve(someGlobal)
        .then(val => { tellSomethingAboutTheGlobal(val); });
}
```

(I'm not sure if any of the above examples are coherent, but I'm struggling to agree that "it is very common to not have a return value.")

**Comment by whymarrh** [comment]
Nonetheless, these rules are just guidelines. As you said, you can declare a `.eslintrc` for the small repos where these rules are more distracting than beneficial.

**Comment by dvalentiate** [comment]
Sorry I seem to have gotten you hung up on `console.log`. I find I'm doing sequential but otherwise independent actions often enough. Passing values isn't the point in those cases.

I think that it is overkill to insist on `return undefined;`. I don't think it makes anything easier. The next .then in the chain needs to look at what it is being passed (or not) no matter what.

**Comment by MitMaro** [comment]
> promise/no-native should be off. Promises are part of the language.

> I don't use Bluebird because it has been an easily dispensed with dependency in the projects I've worked on ? recently. Got nothing against it in bigger projects. But again in small things Bluebird is just bloat.
>
> Let me state it again: Promises are part of the native language. Not an error and not a warning. They are valid and good practice. Bluebird's convention of declaring itself as a native keyword is sketchy (backwards compatibility aside). It is like declaring var Number = {...}; and thinking that is a good idea.

I don't disagree that Bluebird can be overkill for smaller projects and that it can be a lot of bloat for small projects.

However, most of our projects are larger, and there are several reasons why Bluebird is perferred over native promises in those cases. Bluebird provides some additional useful functionality. This includes items such as converting non-promise based async functions to promises using `.promify()/.promisifyAll()`, functional support for promises such as `Promise.map()`, and very good support for showing stacktraces on async promise calls. [This Stackoverflow post](http://stackoverflow.com/a/34961040/124861) gives an excellenet overview. It also, at least currently, [faster than native promises on v8](https://softwareengineering.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird). 

It's an easy enough rule to disable in the projects eslint config file for projects where it isn't needed. But in the general case, we use Bluebird, and it can cause subtle problems when the native promises are used when Bluebird ones are expected.

As for overwritting `Promise`, there isn't any need. If you use `const Bluebird = require('bluebird');` then the no-native rule still holds, and you do not overwrite the builtin `Promise`.

> no-process-env is set to error and that is annoying. On a big project is it very valid to limit the use of environment variables to something like a config file, however when writing scripts using process.env is normal and ok.
>
>Just imagine trying to write a .sh script without using env vars because "those are supposed to be put in a config file".

>I'm open to discussion on this.

Projects should only ever use `process.env` in their main file, or within some sort of configuration loading library/file. The purpose of this rule is to limit it's usage to only those locations and not to have `process.env` sprinkled through out a project. This quickly becomes a maintanance nightmare. I usually just disable this rule using an eslint comment in the file or two that uses `process.env`. For smaller single file projects where this rule makes less sense, this can be disabled in the eslint config file.

> console.log, and console.error are common and ok in scripts, not so much in product code. It is annoying to have it outlawed with no-console set to error.

In the case of scripts it can be disabled in the config file for that project. In general a logger should be used for writing out to stdout in larger projects, or at the very least `console.*` function should be limited to a handful of files.

> promise/always-return should not be set to error. It is common for a promise to not return a value. Such as .then((data) => {console.log(data);})

Cases where you don't return a value from a promise `then` should be fairly rare and can be ignored on a case by case basis, or by returning `null`, `false` or `undefined`. This rule catches the common error of forgetting to return in a promise which can cause odd, often difficult to debug behaviour.

**Comment by dvalentiate** [comment]
By all means use Bluebird all you want. And maybe another library comes along that is better than it even.

But to ban the build in feature of the language...

Libraries that we use can return any type of promise. The only common thing that should be assumed is they match the native promise signature. Await/async are fundamentally native promises.

Good practice is to use the native Promise capabilities and then when going beyond those with something like promisifyAll, use `Bluedird.promisifyAll`. It is explicit, and easy to do. Otherwise if we move to a different promise library or you are using a promise from another library, things will just break.

I disagree with error on `promise/always-return` but see it as reasonable. `no-process-env`, `no-console` are incontinent for me but acceptable. I can't see it as reasonable to promote for a growing and good part of the core language, while encouraging a coding practice that obfuscates. Allowing native promises is must for me.

**Pull request merged**
